excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://RVAMurse.github.io
title: 30:2
email: 
author: RVAMurse
description: A blog dedicated to humanism, the life sciences, nursing advocacy and my personal strategies for just plain dealing with life as a medical professional in the 20-teens.
paginate: 3
google_analytics: 